
//movie advanced search actions
export const MOVIE_TOGGLE_SEARCH = "[MOVIEDB][AD_SEARCH] MOVIE_TOGGLE_SEARCH";
export const MOVIE_GENRE_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] MOVIE_GENRE_SEARCH_CHANGE";
export const MOVIE_REMOVE_GENRE_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] MOVIE_REMOVE_GENRE_SEARCH_CHANGE";
export const MOVIE_ADULT_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] MOVIE_ADULT_SEARCH_CHANGE";
export const MOVIE_VOTE_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] MOVIE_VOTE_SEARCH_CHANGE";
export const MOVIE_TITLE_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] MOVIE_TITLE_SEARCH_CHANGE";
export const MOVIE_OVERVIEW_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] MOVIE_OVERVIEW_SEARCH_CHANGE";
export const MOVIE_APPLY_SEARCH_CONFIG = "[MOVIEDB][AD_SEARCH] MOVIE_APPLY_SEARCH_CONFIG";
export const MOVIE_SAVE_SEARCH_CONFIG = "[MOVIEDB][AD_SEARCH] MOVIE_SAVE_SEARCH_CONFIG";

//show advanced search actions
export const SHOW_TOGGLE_SEARCH = "[MOVIEDB][AD_SEARCH] SHOW_TOGGLE_SEARCH";
export const SHOW_GENRE_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] SHOW_GENRE_SEARCH_CHANGE";
export const SHOW_REMOVE_GENRE_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] SHOW_REMOVE_GENRE_SEARCH_CHANGE";
export const SHOW_ADULT_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] SHOW_ADULT_SEARCH_CHANGE";
export const SHOW_VOTE_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] SHOW_OTE_SEARCH_CHANGE";
export const SHOW_TITLE_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] SHOW_TITLE_SEARCH_CHANGE";
export const SHOW_OVERVIEW_SEARCH_CHANGE = "[MOVIEDB][AD_SEARCH] SHOW_OVERVIEW_SEARCH_CHANGE";
export const SHOW_APPLY_SEARCH_CONFIG = "[MOVIEDB][AD_SEARCH] SHOW_APPLY_SEARCH_CONFIG";
export const SHOW_SAVE_SEARCH_CONFIG = "[MOVIEDB][AD_SEARCH] SHOW_SAVE_SEARCH_CONFIG";
