export const MOVIE_DATA_INIT = "[MOVIEDB][MOVIE] MOVIE_DATA_INIT";
export const MOVIE_DATA_REQUEST = "[MOVIEDB][MOVIE] MOVIE_DATA_REQUEST";
export const MOVIE_DATA_REQUEST_SUCCESS = "[MOVIEDB][MOVIE] MOVIE_DATA_REQUEST_SUCCESS";
export const MOVIE_DATA_REQUEST_ERROR = "[MOVIEDB][MOVIE] MOVIE_DATA_REQUEST_ERROR";
export const GET_MOVIE_DATA = "[MOVIEDB][MOVIE] GET_MOVIE_DATA";