export const MOVIE_DATA_INIT = "[MOVIEDB][MOVIE] MOVIE_DATA_INIT";
export const GET_MOVIE_DATA = "[MOVIEDB][MOVIE] GET_MOVIE_DATA";
export const ADD_USER_MOVIE = "[MOVIEDB][MOVIE] ADD_USER_MOVIE";
export const UPDATE_MOVIE_LIST = "[MOVIEDB][MOVIE] UPDATE_MOVIE_LIST";