export const MYLIB_DATA_INIT = "[MOVIEDB][LIB] MYLIB_DATA_INIT";
export const GET_MYLIB_DATA = "[MOVIEDB][LIB] GET_MYLIB_DATA";
export const MOVIE_ADD_TO_LIB = "[MOVIEDB][LIB] MOVIE_ADD_TO_LIB";
export const TVSHOW_ADD_TO_LIB = "[MOVIEDB][LIB] TVSHOW_ADD_TO_LIB";
export const MOVIE_REMOVE_FROM_LIB = "[MOVIEDB][LIB] MOVIE_REMOVE_FROM_LIB";
export const TVSHOW_REMOVE_FROM_LIB = "[MOVIEDB][LIB] TVSHOW_REMOVE_FROM_LIB";
export const MAKE_ITEMS_WATCHED = "[MOVIEDB][LIB] MAKE_ITEMS_WATCHED";