export const TOGGLE_SCROLL = "[MOVIEDB][SCROLL] TOGGLE_SCROLL";
export const SCROLL_DOWN = "[MOVIEDB][SCROLL] SCROLL_DOWN";
export const SCROLL_UP = "[MOVIEDB][SCROLL] SCROLL_UP";
export const SCROLLING = "[MOVIEDB][SCROLL] SCROLLING";