export const TVSHOW_DATA_INIT = "[MOVIEDB][TVSHOW] TVSHOW_DATA_INIT";
export const GET_TVSHOW_DATA = "[MOVIEDB][TVSHOW] GET_TVSHOW_DATA";
export const ADD_USER_TVSHOW = "[MOVIEDB][TVSHOW] ADD_USER_TVSHOW";
export const TVSHOW_ADDED_TO_LIB = "[MOVIEDB][TVSHOW] TVSHOW_ADDED_TO_LIB";
export const TVSHOW_REMOVED_FROM_LIB = "[MOVIEDB][TVSHOW] TVSHOW_REMOVED_FROM_LIB";
