export const TVSHOW_DATA_INIT = "[MOVIEDB][MOVIE] TVSHOW_DATA_INIT";
export const GET_TVSHOW_DATA = "[MOVIEDB][MOVIE] GET_TVSHOW_DATA";
export const ADD_USER_TVSHOW = "[MOVIEDB][MOVIE] ADD_USER_TVSHOW";
export const TVSHOW_ADDED_TO_LIB = "[MOVIEDB][MOVIE] TVSHOW_ADDED_TO_LIB";
